DROP EXTENSION IF EXISTS pg_stat_statements;
DROP EXTENSION IF EXISTS pgcrypto;
DROP EXTENSION IF EXISTS "uuid-ossp";
DROP EXTENSION IF EXISTS timescaledb;
DROP EXTENSION IF EXISTS postgis_topology;
DROP EXTENSION IF EXISTS postgis;
